title: The DALESdocs
author: The DALES team
logo: _static/daleslogo.png

repository:
  url: https://github.com/dalesteam/dalesdocs
  path_to_book: book/
  branch: main
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true